hydra: 
  run:
    dir: LPD/${benchmark.train_on_noise_level}/${benchmark.normalisation}/${hydra.job.override_dirname}
  sweep:
    dir: LPD/${benchmark.train_on_noise_level}/${benchmark.normalisation}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - benchmark.train_on_noise_level
          - benchmark.normalisation

defaults:
  - _self_
  - dataset: brainweb2Ddataset
  - benchmark: lpd
seed: 1
device: cuda