name: unet 
in_ch: 1
out_ch: 1 
scales: 4
skip: 16
channels: [32, 64, 128, 256]
use_sigmoid: False
use_norm: True
lr: 3e-4
batch_size: 16
epochs: 1000
log_freq: 1000
train_on_noise_level: [5]
normalisation: "none" # "none" "data_mean" "data_quantile" "data_max" "osem_mean" "osem_quantile" "osem_max"
# --multirun benchmark.normalisation="none","data_mean","data_quantile","data_max","osem_mean","osem_quantile","osem_max" benchmark.train_on_noise_level=[5],[10],[50],[5,10,50]